@startuml design

!theme bluegray
skinparam classFontColor darkSlateGray

package "gust" {
  [API {\n  + Store\n}] *-down-* [Store (JSON | SQLite)]
  [CLI] <---> [API {\n  + Store\n}] : API commands\n& responses
  [common types\n and methods] .right. [API {\n  + Store\n}]
  [common types\n and methods] .right. [CLI]
  [common types\n and methods] .right. [Store (JSON | SQLite)]
  [API {\n  + Store\n}] o-right-o [RecipeFetcher]
}
interface "cooking sites (e.g. NYT Cooking , BBC Food)" as ext
[RecipeFetcher] <--down--> ext

@enduml